repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['--config-file=.yamllint.yml']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.yaml]
  - repo: local
    hooks:
      - id: get-requirements-txt-for-cloudflare
        name: Export poetry dependencies to requirements.txt
        entry: .hooks/update_requirements.sh
        language: script
        always_run: false
        files: '^poetry\.lock$'
