---

site_name: Bav Malhi
site_author: Bav Malhi
site_description: >
  site for documentation, practices, how-to-guides, bookmarks and learning
repo_name: bavandeepmalhi/mkdocs-site
repo_url: 'https://github.com/bavandeepmalhi/mkdocs-site'
copyright: Copyright &copy; 2016 - 2024 Bav Malhi
theme:
  name: material
  custom_dir: overrides
  language: en
  icon:
    logo: fontawesome/solid/hat-cowboy
  favicon: images/favicon.png
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.link
    - content.code.copy
    - announce.dismiss
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  markdown_extensions:
    - admonition
    - pymdownx.details
    - attr_list
    - pymdownx.superfences: null
    - pymdownx.emoji: null
    - toc:
        permalink: true
  extra_css:
    - stylesheets/extra.css
  extra:
    social:
      icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/bavmalhi'
nav:
  - Knowledge Base:
      - Start Here:
          - Star Here: index.md
      - Test:
          - Test: test/test.md
